import {ArrowRight,ArrowUpRight,Check,Phone,Star} from 'lucide-react';
import {Header,Footer} from './shell';
import {QuoteForm} from './quote-form';
import {Estimator} from './estimator';
import {businessSchema} from './content';
import './refresh.css';

const reviews='https://www.solarquotes.com.au/installer-review/clean-energy-solutions/';
const questions=[
 ['Is my home suitable for solar?','Your roof, shading, switchboard and electricity use all matter. We review your property before recommending equipment, so the design starts with your home.'],
 ['How much will a system cost?','Your quote depends on the equipment, system size and installation requirements. We explain the scope, upfront price and estimated savings before you decide.'],
 ['Can I add a battery to existing solar?','Often, yes. We check your inverter, available solar surplus and storage needs first. Backup during an outage requires compatible equipment and a suitable installation.'],
 ['What incentives could apply?','Eligibility depends on your property, equipment and the program requirements at the time. We help identify applicable incentives in your quote.'],
];
export function HomePage(){return <><Header/><main id="main" className="ces-home">
<section className="home-hero home-wrap">
 <div className="home-hero__copy"><p className="home-eyebrow">Solar & batteries · Albury-Wodonga</p><h1>Your roof.<br/><span>Lower bills.</span></h1><p className="home-hero__intro">Make your own power. Keep more of it. Get solar and batteries designed for your home, installed by your local CES team.</p><div className="home-actions"><a className="home-button" href="#quote">Get my free quote <ArrowUpRight size={20}/></a><a className="home-text-link" href="#our-work">See our work <ArrowRight size={18}/></a></div><p className="home-assurance"><Check size={16}/> Free advice. Clear pricing. No obligation.</p><a className="home-rating" href={reviews}><span aria-label="5 star graphic" className="home-stars" aria-hidden="true">{[1,2,3,4,5].map(n=><Star key={n} size={15} fill="currentColor"/>)}</span><strong>4.8/5</strong><span>on SolarQuotes <ArrowUpRight size={14}/></span></a></div>
 <figure className="home-hero__photo"><img src="/assets/ces-drone-pool-tile-1200.webp" srcSet="/assets/ces-drone-pool-tile-600.webp 600w, /assets/ces-drone-pool-tile-900.webp 900w, /assets/ces-drone-pool-tile-1200.webp 1200w" sizes="(max-width:760px) 100vw, 55vw" width={1200} height={1200} alt="CES solar installation on a tiled home with a swimming pool" fetchPriority="high"/><figcaption><span>Good energy, closer to home.</span><span>Actual CES installation <ArrowUpRight size={17}/></span></figcaption></figure>
</section>
<div className="home-proof home-wrap"><span>Family-owned in Wodonga</span><span>Our own local electricians</span><span>Support after installation</span></div>
<section id="solutions" className="home-services home-wrap"><div className="home-section-head"><h2>Better energy.<br/>Built around you.</h2><p>Start with solar. Add storage when it makes sense. We’ll help you find the right fit.</p></div><div className="home-service-grid">
<a href="/solar" className="home-service"><img src="/assets/ces-roof-gums-900.webp" alt="Solar panels installed by CES on a corrugated roof" width={900} height={900} loading="lazy"/><div><span>01 / Solar</span><h3>Put your roof to work.</h3><p>Generate power through the day and buy less from the grid.</p><span className="home-service__link">Explore solar <ArrowUpRight size={21}/></span></div></a>
<a href="/batteries" className="home-service"><img src="/assets/ces-garage-byd-fronius-900.webp" alt="CES battery and inverter installation in a garage" width={900} height={675} loading="lazy"/><div><span>02 / Batteries</span><h3>Keep the sun for later.</h3><p>Store surplus solar to use when your home needs it.</p><span className="home-service__link">Explore batteries <ArrowUpRight size={21}/></span></div></a>
</div><a className="home-business" href="/commercial-solar"><span>Powering a business or farm?</span><strong>Let’s put your working hours to work. <ArrowRight size={20}/></strong></a></section>
<Estimator/>
<section id="our-work" className="home-work home-wrap"><div className="home-section-head"><h2>Real roofs.<br/>Real local work.</h2><p>A few installations from our own crews. Thoughtful layouts, tidy work and equipment that suits the property.</p></div><div className="home-work-grid"><figure><img src="/assets/ces-roof-sunset-hills-1200.webp" sizes="(max-width:760px) 100vw, 60vw" srcSet="/assets/ces-roof-sunset-hills-600.webp 600w, /assets/ces-roof-sunset-hills-1200.webp 1200w" width={1200} height={900} loading="lazy" alt="CES rooftop solar array overlooking paddocks and hills at sunset"/><figcaption>Making more of the roof.</figcaption></figure><figure><img src="/assets/ces-powerwalls-enclosure-900.webp" width={900} height={1200} loading="lazy" alt="Two Tesla Powerwall batteries installed by CES in a protective enclosure"/><figcaption>Storage, thoughtfully installed.</figcaption></figure></div><a href="https://www.instagram.com/cesolutions1/" className="home-text-link">More from our crews on Instagram <ArrowUpRight size={18}/></a></section>
<section className="home-local home-wrap"><div className="home-local__photo"><img src="/assets/ces-install-crew-roof.webp" width={721} height={721} loading="lazy" alt="Two CES electricians installing panels on a roof"/></div><div className="home-local__copy"><p className="home-eyebrow">Your local team</p><h2>Good people.<br/>Good energy.</h2><p>Solar is a long-term decision. Choose a team you can talk to before, during and after the installation.</p><ol><li><span>01</span><div><h3>We listen first.</h3><p>Your bills, your home and your plans shape the recommendation.</p></div></li><li><span>02</span><div><h3>You know what you’re getting.</h3><p>Clear equipment choices, installation scope and upfront pricing.</p></div></li><li><span>03</span><div><h3>We’re here afterwards.</h3><p>Our Wodonga team stays available for advice and support.</p></div></li></ol><a className="home-text-link" href="/about">Meet the CES team <ArrowUpRight size={18}/></a></div></section>
<section id="reviews" className="home-review"><div className="home-wrap home-review__inner"><div><div className="home-stars" aria-hidden="true">★★★★★</div><p>From our customers</p><a href={reviews}>Read the SolarQuotes reviews <ArrowUpRight size={17}/></a><small>4.8/5 from 26 ratings, checked 14 September 2026.</small></div><figure><blockquote>“Customer service was excellent, installation was on time and they did a fantastic job. Would definitely recommend.”</blockquote><figcaption>Adam · Albury area · December 2024</figcaption></figure></div></section>
<section id="faq" className="home-faq home-wrap"><div><h2>A little clarity<br/>before you start.</h2><p>Still have a question?<br/><a href="tel:+61260212000">Talk to us on (02) 6021 2000</a></p></div><div>{questions.map(([q,a],i)=><details key={q} id={i===3?'rebates':undefined}><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section>
<section id="quote" className="home-quote"><div className="home-wrap home-quote__inner"><div><p className="home-eyebrow">Let’s talk solar</p><h2>A better energy<br/>plan starts here.</h2><p>Tell us a little about your property. We’ll help you compare your options and take the next step with confidence.</p><a className="home-quote__phone" href="tel:+61260212000"><Phone size={21}/>(02) 6021 2000</a><p className="home-quote__address">79 Elgin Boulevard, Wodonga<br/>Local advice. Free quote. No obligation.</p></div><QuoteForm/></div></section>
</main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({...businessSchema,'@graph':businessSchema['@graph'].filter(x=>x['@type']!=='FAQPage')}).replace(/</g,'\\u003c')}}/></>}
