export const THEME_COLOR='#dceffa';
export const SITE='https://cesolutions.com.au';
export const PREVIEW='https://clean-energy-solutions.higgsfield.app';
export const CONTACT=SITE+'/contact-us/contact-ces/';
export const description='Cut your power bill with solar and batteries designed from your bills and installed by our own local electricians. Family-owned in Wodonga, rated 4.8/5 on SolarQuotes. Call (02) 6021 2000.';
// Answers follow the figures CES publishes on cesolutions.com.au/faq (savings range, payback, install time, rebates).
export const faqs=[
{q:'How much does solar cost in Albury-Wodonga?',a:'It depends on the size of the system, the panels and inverter you choose, and whether you add a battery. A smaller household system might cost a few thousand dollars; larger homes and battery systems cost more. We quote from your bills, so you get a real number, not a range.'},
{q:'How much will I save?',a:'Savings usually range between 50% and 100% of your electricity costs, depending on system size and when you use power. Adding a battery pushes that higher, because you run the evening on your own stored power instead of buying it back at peak rates. We estimate your figure from your actual usage before you commit.'},
{q:'How long until it pays for itself?',a:'Most households see payback within 3 to 6 years, depending on energy use, electricity prices and any rebates. Battery systems can take longer, but they add security and independence. After payback, the power is free for the rest of a 25 to 30 year panel life.'},
{q:'What rebates can I get?',a:'The federal STC discount lowers the upfront cost of panels for everyone. Eligible home batteries get the federal Cheaper Home Batteries discount. Victorian owner-occupiers may also qualify for the Solar Victoria panel rebate. We handle the applications and the distributor paperwork on your behalf.'},
{q:'Does solar work on cloudy days?',a:'Yes, at reduced output. Panels do not generate at night, which is where a battery comes in: it stores your daytime surplus so you can run the house on it after dark.'},
{q:'Can I add a battery later?',a:'Yes. Many people start with panels and add storage when it suits their budget. We design systems to be battery-ready, so you can add one later without major changes to your inverter or switchboard.'}];
export type PageContent={title:string;description:string;heading:string;intro:string;image:string;alt:string;sections:{title:string;body:string}[]};
export const pages:Record<string,PageContent>={
solar:{title:'Solar Installers Albury-Wodonga | Clean Energy Solutions',description:'Residential solar installation in Albury-Wodonga. Local design, in-house electricians and ongoing support from Clean Energy Solutions. Request a tailored quote.',heading:'Solar that fits\nyour life.',intro:'Residential solar in Albury-Wodonga, designed around your roof, your electricity bills and the way you live. Most CES households cut their power bill by 50–100%.',image:'instagram-rooftop.webp',alt:'Solar panels on a metal roof, shared by CES on Instagram',sections:[
{title:'Start with your home.',body:'Your home has its own pattern of energy use. Working from home, running cooling through summer or planning an electric vehicle can all influence the design. Clean Energy Solutions reviews your electricity bills, available roof space and future plans before recommending a system. We explain the panel layout, inverter options and practical installation requirements in plain language.'},
{title:'Make more use of your sunshine.',body:'Solar panels convert sunlight into electricity. An inverter converts that energy into power your home can use. Running suitable appliances during the day can help you use more of your own generation. Surplus may be exported to the grid, subject to network arrangements, or stored in a compatible battery. Your result depends on your equipment, tariff and consumption.'},
{title:'A local team through every step.',body:'Our team coordinates the design and installation, explains how your system works and helps you understand monitoring. You have a local point of contact after the work is complete. We will talk through product choices, warranties, network requirements and any eligible incentives as part of your quote, so the scope is clear before you make a commitment.'}]},
batteries:{title:'Home Battery Installation Albury-Wodonga | CES',description:'Store your solar for later with a home battery in Albury-Wodonga. Explore compatibility, backup options and a tailored battery design with Clean Energy Solutions.',heading:'Keep your solar\nfor after sunset.',intro:'Home batteries in Albury-Wodonga store your daytime surplus so you run the evening on your own power instead of buying it back at peak rates.',image:'battery.webp',alt:'Home battery system featured by Clean Energy Solutions',sections:[
{title:'Use your solar after sunset.',body:'A battery stores energy for later use. For households with spare daytime solar and evening demand, storage can reduce the need to buy electricity from the grid. The right battery size depends on how much surplus you generate and how much power you use after dark. Bigger is not automatically better: we start with your usage and the practical limits of your site.'},
{title:'Choose the right fit for your system.',body:'Clean Energy Solutions offers battery options including Tesla, BYD, Sungrow and Sigenergy. A retrofit assessment checks your existing inverter, switchboard and system configuration. If you are starting fresh, solar and storage can be designed together. We explain usable storage, power output, warranty terms and monitoring so you can make a useful comparison.'},
{title:'Be clear about backup and incentives.',body:'Blackout protection is a specific design requirement, not an automatic feature of every battery installation. Tell us which appliances matter during an outage so we can discuss compatible equipment and backup circuits. Eligible systems may receive support through the Australian Government Cheaper Home Batteries Program. Eligibility and the applicable discount should be confirmed for your installation date.'}]},
'commercial-solar':{title:'Commercial Solar Albury-Wodonga | Clean Energy Solutions',description:'Solar for businesses in Albury-Wodonga. Match a commercial solar system to your operating hours, roof and electricity use with the local CES team.',heading:'Make your working hours\nwork for your bill.',intro:'Commercial solar in Albury-Wodonga, planned around the hours your business works and the electricity it uses.',image:'instagram-crew.webp',alt:'CES team at their workplace, from CES Instagram',sections:[
{title:'Build the business case from your bills.',body:'A commercial system should be assessed against the way your business actually operates. Daytime electricity demand can be well matched to solar generation, but the details matter. We review your usage, operating hours, available roof area and future plans to identify a practical starting point. Equipment capacity and projected savings should follow the evidence in that assessment.'},
{title:'Plan for the site and the schedule.',body:'Every premises has different access, electrical and roof requirements. Clean Energy Solutions discusses installation scope, site access and scheduling with you before work begins. We explain network connection considerations and any further checks required, so you understand the path from an initial design to a working system. Your quote sets out the proposed equipment and work.'},
{title:'Make ongoing performance understandable.',body:'Monitoring helps you understand generation and how it relates to your business consumption. Our local team provides guidance on using your system and is available for follow-up support. If storage may suit your operation, we can discuss battery compatibility, consumption patterns and any backup requirements separately. The aim is an energy system you can understand and manage with confidence.'}]},
about:{title:'Meet Your Local Solar Team | Clean Energy Solutions',description:'Meet Bree and Daniel Grubisa and the local Clean Energy Solutions team in Wodonga. Personal solar advice, in-house electricians and ongoing support.',heading:'The people who’ll\nbe on your roof.',intro:'Clean Energy Solutions is a family-owned solar and battery business in Wodonga. Bree designs the system, Daniel’s crew installs it, and the same people answer the phone afterwards.',image:'daniel.webp',alt:'Daniel Grubisa, Clean Energy Solutions electrician and solar installer',sections:[
{title:'Meet Bree and Daniel.',body:'Bree and Daniel Grubisa are the husband-and-wife team behind Clean Energy Solutions, supported by dedicated staff and in-house electricians. Daniel is a qualified electrician and solar installer with more than 15 years in the industry. Bree helps customers understand their options and the decisions involved in choosing a system. Together, the team brings practical installation knowledge and a personal approach to solar advice.'},
{title:'Good advice starts with listening.',body:'Your energy needs are the starting point. We take time to understand your household or business, explain how solar interacts with the grid and discuss what a battery could change. We want you to know what the equipment does, why it has been recommended and what the expected results depend on. A clear conversation now helps you make a better decision for the long term.'},
{title:'Still here after installation.',body:'Our role continues once your system is running. We help you understand monitoring, use your system confidently and know where to turn for support. Contact the team at 79 Elgin Boulevard, Wodonga, Victoria 3690, call (02) 6021 2000 or email info@cesolutions.com.au. If you are outside Albury-Wodonga, ask us to confirm service availability for your address.'}]}};
export function pageHead(title:string,desc:string,path:string){return{meta:[{title},{name:'description',content:desc},{property:'og:title',content:title},{property:'og:description',content:desc},{property:'og:url',content:SITE+path}],links:[{rel:'canonical',href:SITE+path}]};}
export const businessSchema={'@context':'https://schema.org','@graph':[{'@type':'LocalBusiness','@id':SITE+'/#business',name:'Clean Energy Solutions',url:SITE,logo:PREVIEW+'/assets/logo.png',image:PREVIEW+'/assets/instagram-rooftop.webp',telephone:'+61260212000',email:'info@cesolutions.com.au',description:'Family-owned solar and battery business serving homes and businesses in Albury-Wodonga.',address:{'@type':'PostalAddress',streetAddress:'79 Elgin Boulevard',addressLocality:'Wodonga',addressRegion:'VIC',postalCode:'3690',addressCountry:'AU'},areaServed:[{'@type':'City',name:'Albury'},{'@type':'City',name:'Wodonga'}]},{'@type':'WebSite','@id':SITE+'/#website',name:'Clean Energy Solutions',url:SITE,publisher:{'@id':SITE+'/#business'}},{'@type':'FAQPage',mainEntity:faqs.map(f=>({'@type':'Question',name:f.q,acceptedAnswer:{'@type':'Answer',text:f.a}}))}]};
