import {useEffect,useRef,useState} from 'react';
import {useScroll} from 'motion/react';
import {ScrollChars,ScrollPhotos} from '@/components/ui/text-scroll-animation';
import {Arrow} from './shell';
import {MAPS,Kicker} from './sections';
import {SITE} from './content';
import {Parallax,Rise} from './motion';
/* Public Instagram posts and photographs from cesolutions.com.au (sources in asset-sources.json). Titles say
 * what the photo shows; the `kind` line is what a visitor scans. No invented sizes, locations or results. */
type Work={id:string;category:'Solar'|'Batteries'|'Our team';shape:'portrait'|'landscape';image:string;width:number;height:number;kind:string;title:string;body:string;href:string;source:string;alt:string;feature?:boolean};
const work:Work[]=[
{id:'drone',category:'Solar',shape:'landscape',feature:true,image:'instagram-roof-drone.webp',width:1600,height:1600,kind:'Residential · rooftop solar',title:'Black-on-red, from above.',body:'All-black panels laid out on a red corrugated roof. The drone shot is how we check a layout on install day.',href:'https://www.instagram.com/cesolutions1/p/Dccg6arnFf3/',source:'@cesolutions1 · Aug 2026',alt:'Drone view of black solar panels on a red corrugated roof, installed by CES'},
{id:'shed',category:'Solar',shape:'portrait',image:'instagram-shed.webp',width:1600,height:1600,kind:'Shed · farm & rural',title:'A whole shed roof of panels.',body:'Sheds, workshops and farm buildings are some of the best solar hosts we work with: big, simple roofs and daytime demand.',href:'https://www.instagram.com/cesolutions1/p/DciM1ayIAv3/',source:'@cesolutions1 · Aug 2026',alt:'Black solar panels across a new shed roof, installed by CES'},
{id:'roof',category:'Solar',shape:'portrait',image:'instagram-rooftop.webp',width:1200,height:1500,kind:'Residential · rooftop solar',title:'Panels on a metal roof.',body:'Standard corrugated roof, clean rail layout. Photographed by the crew before they packed up.',href:'https://www.instagram.com/cesolutions1/p/DdBGXypjZuT/',source:'@cesolutions1 · Sep 2026',alt:'Solar panels on a metal roof beneath a cloudy sky, photographed by CES'},
{id:'battery',category:'Batteries',shape:'landscape',image:'battery.webp',width:1500,height:1000,kind:'Home battery · wall-mounted',title:'Battery and inverter, tidy.',body:'Mounted on an external wall with the conduit run neatly. Backup, capacity and placement are all part of the design chat.',href:SITE+'/battery-products/',source:'cesolutions.com.au',alt:'Home battery and inverter mounted on a timber-clad exterior wall'},
{id:'daniel',category:'Our team',shape:'portrait',image:'daniel.webp',width:900,height:1200,kind:'Our team · on the roof',title:'Daniel, mid-install.',body:'A licensed electrician with more than 15 years installing solar on the Border, and the person who leads our crews.',href:SITE+'/contact-us/daniel-grubisa/',source:'cesolutions.com.au',alt:'Daniel Grubisa in a hi-vis shirt on a roof beside newly installed solar panels'},
{id:'people',category:'Our team',shape:'landscape',image:'instagram-crew.webp',width:1600,height:1060,kind:'Our team · the crew',title:'The people behind the panels.',body:'The installers, designers and office team, all on one payroll in Wodonga.',href:'https://www.instagram.com/cesolutions1/p/DdAkDIQIPCf/',source:'@cesolutions1 · Sep 2026',alt:'The CES team together at their workplace'},
{id:'people-close',category:'Our team',shape:'portrait',image:'instagram-team.webp',width:1200,height:1500,kind:'Our team · your first call',title:'The people you’ll actually talk to.',body:'Ask us about your bills, your roof or the system you already have. We answer in plain language.',href:'https://www.instagram.com/cesolutions1/p/DdISbZLDSY9/',source:'@cesolutions1 · Sep 2026',alt:'Two CES team members in company uniforms'},
{id:'shop',category:'Our team',shape:'landscape',image:'team.webp',width:1800,height:992,kind:'Our office · Wodonga',title:'79 Elgin Boulevard.',body:'Drop in with a bill and we’ll talk it through in person.',href:MAPS,source:'cesolutions.com.au',alt:'The Clean Energy Solutions shopfront on a red-brick corner building'}];
const filters=['All','Solar','Batteries','Our team'] as const;
/** Pinned intro: the words "Our work" converge and the photos fan in as the section scrolls. */
function WorkIntro(){
  const ref=useRef<HTMLDivElement>(null);
  const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});
  const photos=work.slice(0,6).map(p=>({src:'/assets/'+p.image,alt:p.alt,width:p.width,height:p.height,href:p.href}));
  return <div ref={ref} className="work-intro"><div className="work-intro__pin"><Kicker light>Real installs, real people</Kicker><h2 className="work-intro__title"><ScrollChars text="Our work" progress={scrollYProgress}/></h2><ScrollPhotos photos={photos} progress={scrollYProgress} className="work-fan" itemClassName="work-fan__item" spread={120} tilt={10} drop={28}/><p className="work-intro__caption">Photography from our crews and <a href="https://www.instagram.com/cesolutions1/">@cesolutions1</a>. Nothing staged, nothing stock.</p></div></div>;
}
export function ProjectGallery(){
  const [filter,setFilter]=useState<(typeof filters)[number]>('All');
  const visible=work.filter(p=>filter==='All'||p.category===filter);
  const counts=Object.fromEntries(filters.map(f=>[f,f==='All'?work.length:work.filter(p=>p.category===f).length]));
  return <section id="our-work" className="work-section"><WorkIntro/><div className="wrap">
    <div className="work-controls" role="group" aria-label="Filter CES photos">{filters.map(v=><button key={v} type="button" aria-pressed={filter===v} onClick={()=>setFilter(v)}>{v}<span className="work-controls__n">{counts[v]}</span></button>)}</div>
    <div className="work-masonry" key={filter}>{visible.map((p,i)=><Rise key={p.id} delay={Math.min(i,4)*.06}><article className={'work-card'+(p.feature&&filter==='All'?' work-card--feature':'')} data-shape={p.shape}><a className="work-image" href={p.href} aria-label={'View original: '+p.title}><Parallax intensity={p.feature?36:22}><img src={'/assets/'+p.image} alt={p.alt} width={p.width} height={p.height} loading="lazy" decoding="async"/></Parallax><span className="work-card__kind">{p.kind}</span><span className="work-card__open" aria-hidden="true"><Arrow/></span></a><div className="work-card__body"><h3><a href={p.href}>{p.title}</a></h3><p>{p.body}</p><span className="work-card__source">{p.source}</span></div></article></Rise>)}</div>
    <div className="work-more"><p>Want to see a system like yours? Ask Ella for install photos from your area.</p><a className="instagram-link" href="https://www.instagram.com/cesolutions1/">Follow @cesolutions1 <Arrow/></a></div>
  </div></section>;
}
export function SiteMotion(){useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');const active=new Set<Animation>();let observer:IntersectionObserver|undefined;const stop=()=>{observer?.disconnect();for(const a of active)a.cancel();active.clear();};const start=()=>{stop();if(motion.matches)return;observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){const a=e.target.animate([{transform:'translateY(14px)'},{transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.65,.3,1)',fill:'none'});active.add(a);a.onfinish=()=>active.delete(a);observer?.unobserve(e.target);}}},{threshold:.12});document.querySelectorAll('.section-heading,.team-copy,.reason-list article,.process-list article').forEach(el=>observer?.observe(el));};start();motion.addEventListener('change',start);return()=>{stop();motion.removeEventListener('change',start);};},[]);return null;}
