import {useEffect,useRef,useState} from 'react';
import {useScroll} from 'motion/react';
import {ScrollChars,ScrollPhotos} from '@/components/ui/text-scroll-animation';
import {Arrow} from './shell';
import {MAPS} from './sections';
import {SITE} from './content';
import {Parallax,ParallaxColumns,Rise} from './motion';
// Three public Instagram posts plus three photographs from cesolutions.com.au (sources in asset-sources.json). No invented sizes, locations or results.
const work=[{id:'roof',category:'Solar',shape:'portrait',image:'instagram-rooftop.webp',width:512,height:640,title:'A closer look at rooftop solar.',body:'Panel layout, roof access and the view from the job. Installation photography shared by our team.',href:'https://www.instagram.com/cesolutions1/p/DdBGXypjZuT/',source:'CES Instagram · 8 September 2026',alt:'Solar panels on a metal roof beneath a cloudy sky, photographed by CES'},
{id:'people',category:'Our team',shape:'landscape',image:'instagram-crew.webp',width:640,height:427,title:'The people behind the panels.',body:'Local faces, practical experience and a team you can get to know before your installation.',href:'https://www.instagram.com/cesolutions1/p/DdAkDIQIPCf/',source:'CES Instagram · 7 September 2026',alt:'The CES team together at their workplace'},
{id:'daniel',category:'Solar',shape:'portrait',image:'daniel.webp',width:900,height:1200,title:'Daniel, on the roof.',body:'A licensed electrician with more than 15 years installing solar on the Border, and the person who leads our crews.',href:SITE+'/contact-us/daniel-grubisa/',source:'cesolutions.com.au',alt:'Daniel Grubisa in a hi-vis shirt on a roof beside newly installed solar panels'},
{id:'battery',category:'Batteries',shape:'landscape',image:'battery.webp',width:1500,height:1000,title:'A home battery, wall-mounted.',body:'Battery and inverter on an external wall. Backup, compatibility and storage size are all part of the design conversation.',href:SITE+'/battery-products/',source:'cesolutions.com.au',alt:'Home battery and inverter mounted on a timber-clad exterior wall'},
{id:'people-close',category:'Our team',shape:'portrait',image:'instagram-team.webp',width:512,height:640,title:'A conversation with your local team.',body:'Get to know the people you can call about your bills, your roof and your plans for solar.',href:'https://www.instagram.com/cesolutions1/p/DdISbZLDSY9/',source:'CES Instagram · 10 September 2026',alt:'Two CES team members in company uniforms'},
{id:'shop',category:'Our team',shape:'landscape',image:'team.webp',width:1024,height:562,title:'Our shopfront in Wodonga.',body:'On the corner of Elgin Boulevard. Drop in with a bill and we’ll talk it through.',href:MAPS,source:'cesolutions.com.au',alt:'The Clean Energy Solutions shopfront on a red-brick corner building'}];
const filters=['All','Solar','Batteries','Our team'];
/** Pinned intro: the words "Our work" converge and the photos fan in as the section scrolls (skiperui pattern). */
function WorkIntro(){
  const ref=useRef<HTMLDivElement>(null);
  const {scrollYProgress}=useScroll({target:ref,offset:['start end','end start']});
  const photos=work.map(p=>({src:'/assets/'+p.image,alt:p.alt,width:p.width,height:p.height,href:p.href}));
  return <div ref={ref} className="work-intro"><div className="work-intro__pin"><span className="kicker kicker--light"><span aria-hidden="true" className="kicker__bl"/><span aria-hidden="true" className="kicker__tr"/>Our impact</span><h2 className="work-intro__title"><ScrollChars text="Our work" progress={scrollYProgress}/></h2><ScrollPhotos photos={photos} progress={scrollYProgress} className="work-fan" itemClassName="work-fan__item" spread={120} tilt={10} drop={28}/><p className="work-intro__caption">Real roofs and real people — from <a href="https://www.instagram.com/cesolutions1/">@cesolutions1</a> and cesolutions.com.au.</p></div></div>;
}
export function ProjectGallery(){const [filter,setFilter]=useState('All');const visible=work.filter(p=>filter==='All'||p.category===filter);return <section id="our-work" className="work-section"><WorkIntro/><div className="wrap"><div className="work-controls" role="group" aria-label="Filter CES photos">{filters.map(v=><button key={v} type="button" aria-pressed={filter===v} onClick={()=>setFilter(v)}>{v}</button>)}<span role="status" className="work-count">{visible.length} {visible.length===1?'story':'stories'}</span></div><ParallaxColumns key={filter} className="work-grid">{visible.map((p,i)=><Rise key={p.id} delay={i*.06}><article className="work-card" data-shape={p.shape}><a className="work-image" href={p.href} aria-label={'View original: '+p.title}><Parallax intensity={p.shape==='portrait'?40:26}><img src={'/assets/'+p.image} alt={p.alt} width={p.width} height={p.height} loading="lazy" decoding="async"/></Parallax><span aria-hidden="true"><Arrow/></span></a><div className="work-meta"><span>{p.category}</span><span>{p.source}</span></div><h3><a href={p.href}>{p.title}</a></h3><p>{p.body}</p><a className="work-link" href={p.href}>View original <Arrow/></a></article></Rise>)}</ParallaxColumns><a className="instagram-link" href="https://www.instagram.com/cesolutions1/">More from @cesolutions1 <Arrow/></a></div></section>}
export function SiteMotion(){useEffect(()=>{const motion=matchMedia('(prefers-reduced-motion: reduce)');const active=new Set<Animation>();let observer:IntersectionObserver|undefined;const stop=()=>{observer?.disconnect();for(const a of active)a.cancel();active.clear();};const start=()=>{stop();if(motion.matches)return;observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting){const a=e.target.animate([{transform:'translateY(14px)'},{transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.2,.65,.3,1)',fill:'none'});active.add(a);a.onfinish=()=>active.delete(a);observer?.unobserve(e.target);}}},{threshold:.12});document.querySelectorAll('.section-heading,.team-copy,.reason-list article,.process-list article').forEach(el=>observer?.observe(el));};start();motion.addEventListener('change',start);return()=>{stop();motion.removeEventListener('change',start);};},[]);return null;}
