import {useEffect,useRef,useState} from 'react';
import {Facebook,Instagram} from './nav';
export {Header} from './nav';
import {ArrowRight,Mail,MapPin,Phone} from 'lucide-react';
import {CONTACT,faqs} from './content';
import {Reveal,Rise} from './motion';
const MAPS_LINK='https://www.google.com/maps/search/?api=1&query=79%20Elgin%20Boulevard%20Wodonga%20Victoria%203690';
export function Arrow(){return <span aria-hidden="true">↗</span>}
const footerColumns=[
{title:'Services',links:[['Residential solar','/solar'],['Home batteries','/batteries'],['Commercial solar','/commercial-solar'],['How it works','/#flow-heading']]},
{title:'Company',links:[['Our team','/about'],['Our work','/#our-work'],['Reviews','/#reviews'],['Get my free quote','/#quote']]},
{title:'Areas',links:[['Albury-Wodonga','/'],['Wagga Wagga','/locations/wagga-wagga'],['Shepparton','/locations/shepparton'],['Yarrawonga','/locations/yarrawonga']]}];
/** Glass-card footer on the black base with a soft brand glow (adapted from mvpblocks' FooterGlow). */
export function Footer(){return <footer className="site-footer glow-footer"><div className="glow-footer__blobs" aria-hidden="true"><span/><span/></div><div className="glow-footer__card wrap"><div className="glow-footer__brand"><a href="/" className="brand footer-brand" aria-label="Clean Energy Solutions home"><img src="/assets/logo-wide-420.webp" width="420" height="120" alt="Clean Energy Solutions"/></a><p>Family-owned solar and battery installers on the Border. Designed from your bills, installed by our own electricians, supported by people you can call.</p><ul className="glow-footer__social" aria-label="Social links"><li><a href="https://www.facebook.com/CESolutionsNSW/" aria-label="CES on Facebook"><Facebook size={20} aria-hidden="true"/></a></li><li><a href="https://www.instagram.com/cesolutions1/" aria-label="CES on Instagram"><Instagram size={20} aria-hidden="true"/></a></li></ul></div><nav className="glow-footer__nav" aria-label="Footer navigation">{footerColumns.map(c=><div key={c.title}><h3>{c.title}</h3><ul>{c.links.map(([label,href])=><li key={href}><a href={href}>{label}</a></li>)}</ul></div>)}<div><h3>Contact</h3><ul className="glow-footer__contact"><li><a href="tel:+61260212000"><Phone size={18} aria-hidden="true"/>(02) 6021 2000</a></li><li><a href="mailto:info@cesolutions.com.au"><Mail size={18} aria-hidden="true"/>info@cesolutions.com.au</a></li><li><a href={MAPS_LINK}><MapPin size={18} aria-hidden="true"/><address>79 Elgin Boulevard<br/>Wodonga, Victoria 3690</address></a></li></ul></div></nav></div><div className="footer-bottom wrap"><span>© {new Date().getFullYear()} Clean Energy Solutions</span><a href="/privacy">Privacy policy</a><span>Albury · Wodonga</span></div></footer>}
export function ContactBand(){return <section className="contact-band"><div><Reveal lines={['Ready to see','your number?']}/><Rise delay={.2}><p>Send us a recent bill or book a free site visit. You’ll get a system designed from your usage, expected savings and clear pricing — free, no obligation.<br/>No pressure, no call centre.</p><a className="contact-band-link" href="/contact">Get my free quote <ArrowRight size={18} aria-hidden="true"/></a></Rise></div><Rise className="contact-band-aside" delay={.3}><span>Talk to your local team</span><a href="tel:+61260212000">(02) 6021 2000</a><p>Local advice, our own electricians, 4.8/5 on SolarQuotes.</p></Rise></section>}
export function Faq(){return <section id="faq" className="faq-section wrap"><div><span className="kicker"><span aria-hidden="true" className="kicker__bl"/><span aria-hidden="true" className="kicker__tr"/>FAQ</span><Reveal lines={['Questions?','We’ve got answers.']}/><p>Quick answers to the most common questions about solar, batteries, installation and savings.</p><a className="faq-phone" href="tel:+61260212000">Call the local team <Arrow/></a></div><div className="faq-list">{faqs.map((f,i)=><Rise key={f.q} delay={i*.06}><details open={i===0}><summary>{f.q}<span aria-hidden="true">+</span></summary><p>{f.a}</p></details></Rise>)}</div></section>}
