import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {Outlet,createRootRouteWithContext,HeadContent,Scripts,useRouter} from '@tanstack/react-router';
import {useEffect,type ReactNode} from 'react';
import {MotionConfig} from 'motion/react';
import appCss from '../styles.css?url';
import appMeta from '../app-meta.json';
import {reportHiggsfieldError} from '../lib/higgsfield-error-reporting';
import {SITE,THEME_COLOR} from '@/site/content';
declare const __HF_DESIGN_INSPECTOR__:boolean;
function NotFound(){return <main id="main" className="error-page"><p>404 / Clean Energy Solutions</p><h1>A little off the sunny path.</h1><p>This page could not be found.</p><a href="/">Back to home ↗</a></main>}
function ErrorPage({reset}:{reset:()=>void}){const router=useRouter();return <main id="main" className="error-page"><h1>This page needs another try.</h1><p>Refresh the page or call our team on (02) 6021 2000.</p><button onClick={()=>{void router.invalidate();reset();}}>Try again</button><a href="/">Back to home</a></main>}
export const Route=createRootRouteWithContext<{queryClient:QueryClient}>()({head:()=>({meta:[{charSet:'utf-8'},{name:'viewport',content:'width=device-width, initial-scale=1'},{title:appMeta.og_title},{name:'description',content:appMeta.og_description},{name:'author',content:'Clean Energy Solutions'},{name:'theme-color',content:THEME_COLOR},{name:'robots',content:'index, follow, max-image-preview:large'},{property:'og:title',content:appMeta.og_title},{property:'og:description',content:appMeta.og_description},{property:'og:type',content:'website'},{property:'og:locale',content:'en_AU'},{property:'og:site_name',content:'Clean Energy Solutions'},{property:'og:image',content:SITE+'/assets/ces-og-wide.png'},{name:'twitter:card',content:'summary_large_image'},{name:'twitter:image',content:SITE+'/assets/ces-og-wide.png'}],links:[{rel:'stylesheet',href:appCss},{rel:'icon',href:'/assets/favicon.png'},{rel:'apple-touch-icon',href:'/assets/apple-touch-icon.png'},{rel:'manifest',href:'/site.webmanifest'}]}),shellComponent:RootShell,component:RootComponent,notFoundComponent:NotFound,errorComponent:ErrorPage});
// Netlify's edge injects a hosting comment and two <meta> tags after <meta charset>, and a HUD <script> after
// </html> (which the parser moves into <body>), each wrapped in newlines. React hydrates the whole document
// here, so those nodes — the whitespace text nodes above all — fail hydration. This runs first, sweeps what
// already exists and removes the rest as the parser inserts it, then stops at load.
const stripHostInjection="(function(){var c=function(n){var p=n.parentNode;if(!p)return;if(n.nodeType===8&&/Netlify/.test(n.data))n.remove();else if(n.nodeType===3&&!n.data.trim()&&(p===document.head||p===document.body))n.remove();else if(n.nodeName==='META'&&/^(hosting-provider|netlify-deploy)$/.test(n.getAttribute('name')||''))n.remove();else if(n.nodeName==='SCRIPT'&&/^\\/\\.netlify\\//.test(n.getAttribute('src')||''))n.remove()};Array.prototype.slice.call(document.head.childNodes).forEach(c);var o=new MutationObserver(function(rs){rs.forEach(function(r){Array.prototype.slice.call(r.addedNodes).forEach(c)})});o.observe(document.documentElement,{childList:true,subtree:true});addEventListener('load',function(){setTimeout(function(){o.disconnect()},1000)})})()";
// Motion writes entrance start states inline; with scripts off, the noscript sheet forces everything visible.
function RootShell({children}:{children:ReactNode}){return <html lang="en-AU" style={{colorScheme:'light'}}><head><script dangerouslySetInnerHTML={{__html:stripHostInjection}}/><HeadContent/><noscript><style>{'[data-motion]{opacity:1!important;transform:none!important}'}</style></noscript></head><body>{children}<Scripts/></body></html>}
function RootComponent(){const {queryClient}=Route.useRouteContext();useEffect(()=>{if(!__HF_DESIGN_INSPECTOR__)return;void import('../module/design-inspector/runtime').then(({installHiggsfieldDesignInspector})=>installHiggsfieldDesignInspector()).catch(e=>reportHiggsfieldError(e instanceof Error?e:new Error('Design inspector unavailable'),{boundary:'design_inspector'}));},[]);return <QueryClientProvider client={queryClient}><MotionConfig reducedMotion="user"><Outlet/></MotionConfig></QueryClientProvider>}
