import {createFileRoute} from '@tanstack/react-router';
import {Header,Footer,ContactBand,Faq,Arrow} from '@/site/shell';
import {businessSchema,description,pageHead} from '@/site/content';
import {ProjectGallery} from '@/site/projects';
import {Hero,ServiceStack,VisitBand,WhatWeDo} from '@/site/sections';
import {ProcessMotion,SystemFlow} from '@/site/flow';
import {ReviewMarquee} from '@/site/reviews';
import {Counter,Float,Marquee,Parallax,Reveal,RevealWords,Rise,ScrollWords} from '@/site/motion';
export const Route=createFileRoute('/')({head:()=>pageHead('Solar & Battery Installers Albury-Wodonga | Clean Energy Solutions',description,'/'),component:Home});
const brands=['Tesla','Sungrow','Sigenergy','BYD','Fronius','Enphase','Jinko'];
function Home(){return <><Header/><main id="main"><Hero/><WhatWeDo/>
<section className="trust-strip" aria-label="Why choose Clean Energy Solutions"><div><strong><Counter value={4.8} decimals={1}/><span className="unit">/5</span></strong><span>Rated by 26 customers on SolarQuotes</span></div><div><strong><Counter value={15} suffix="+"/></strong><span>Years Daniel has installed solar on the Border</span></div><div><strong>In-house</strong><span>Our own CEC-accredited electricians, led by Daniel</span></div><div><strong><Counter value={1}/> day</strong><span>Most home systems are installed in a single day</span></div></section>
<section id="solutions" className="services-section wrap"><div className="section-heading"><Reveal lines={['Three ways to','buy less power.']}/><Rise delay={.15}><p>Start with your electricity bills. We’ll work out whether solar, a battery or both make sense for your place, and show you the numbers before you sign.</p></Rise></div><ServiceStack/></section>
<SystemFlow/>
<section className="manifesto" aria-label="How CES works"><div className="wrap"><span className="eyebrow">Solar, explained properly</span><ScrollWords className="manifesto-text" text="Solar isn’t complicated once someone explains it properly. We read your bills, design around how you actually use power, install it with our own electricians, and answer the phone when you call afterwards."/></div></section>
<ProjectGallery/>
<section className="reason-section wrap"><div><Reveal lines={['What you get with CES','that a call centre','can’t give you.']}/><Rise delay={.2}><p className="reason-intro">Solar sold over the phone comes as a package. Ours starts with your bills, your roof and what you’re planning next.</p></Rise></div><div className="reason-list"><Rise><article><span>01</span><div><h3>One team, start to finish.</h3><p>Bree designs it. Daniel’s crew installs it. The same people answer the phone afterwards. No handballing, no “I’ll have to check with the installer.”</p></div></article></Rise><Rise delay={.1}><article><span>02</span><div><h3>Sized to your bills, not a package.</h3><p>Every system is designed from your recent bills, your roof and what’s coming next: an EV, a battery, a pool. You see the expected output and savings before you sign.</p></div></article></Rise><Rise delay={.2}><article><span>03</span><div><h3>You’ll see the savings live.</h3><p>Every system comes with a monitoring app that shows what you’re generating, using and exporting in real time. We set it up on your phone before we leave.</p></div></article></Rise></div></section>
<section className="team-section wrap"><div className="team-collage"><div className="team-visual"><Parallax className="team-media" intensity={28}><img src="/assets/instagram-team.webp" alt="Two members of the Clean Energy Solutions team in CES uniforms" width="512" height="640" loading="lazy"/></Parallax><p>Your local solar people<br/><a href="https://www.instagram.com/cesolutions1/p/DdISbZLDSY9/">From @cesolutions1 ↗</a></p></div><Float className="team-inset" y={[70,-70]}><img src="/assets/instagram-crew.webp" alt="The wider CES crew at their Wodonga workplace" width="640" height="427" loading="lazy"/></Float></div><div className="team-copy"><span className="eyebrow">Meet Clean Energy Solutions</span><Reveal lines={['Meet the people','who’ll actually be','on your roof.']}/><Rise delay={.2}><p className="large-body">We’re Bree and Daniel Grubisa, a family-owned business in Wodonga.</p><p>Daniel is a licensed electrician who has been installing solar on the Border for over 15 years. Bree runs the design side: she visits your home, reads your bills and designs a system around how you actually use power.</p><p>Our electricians are on our payroll, not subcontracted. The person who quotes you and the person who installs it work in the same building.</p><a className="team-link" href="/about">Meet your team <Arrow/></a></Rise></div></section>
<section className="brand-section"><p>Equipment we install and help you compare</p><Marquee items={brands} label="Equipment brands offered by CES"/></section>
<section id="reviews" className="review-section"><div className="wrap"><a className="review-score" href="https://www.solarquotes.com.au/installer-review/clean-energy-solutions/"><strong>4.8<span>/5</span></strong><span>26 SolarQuotes ratings<br/><small>Checked 14 September 2026 · Read reviews ↗</small></span></a><h2 className="sr-only">What CES customers say</h2><RevealWords as="blockquote" text="“A professional and very seamless process from start to finish.”"/><Rise delay={.3}><p className="review-detail">Bree visited promptly after the first enquiry and answered every question. Three weeks later Jacob installed the new panels, battery and inverter in a day.</p><p>Lois Nolan <span>· CES customer</span></p><a href="https://cesolutions.com.au/clean-energy-solutions-book-online/">Read Lois’s full review <Arrow/></a></Rise></div><ReviewMarquee/></section>
<VisitBand/>
<section className="process-section wrap"><Reveal lines={['From your first bill','to your first solar day.']}/><div className="process-list"><span className="process-line" aria-hidden="true"><i/></span><ProcessMotion/><Rise><article><span>01 / Send a bill</span><div><h3>Tell us about your place.</h3><p>A recent electricity bill and a quick chat about your plans give us everything we need to start.</p></div></article></Rise><Rise delay={.1}><article><span>02 / Site visit &amp; design</span><div><h3>Get a design, a savings estimate and a fixed quote.</h3><p>Bree checks the roof and designs around how you use power. You see the expected output and savings before you decide.</p></div></article></Rise><Rise delay={.2}><article><span>03 / Install &amp; switch on</span><div><h3>Installed by our crew. Usually in a day.</h3><p>Our electricians install it, handle the distributor paperwork and set up the monitoring app on your phone before they leave.</p></div></article></Rise></div></section>
<section className="rebate-section wrap"><div><Reveal lines={['Two rebates are','open right now.']}/><Rise delay={.2}><p>The federal Cheaper Home Batteries Program discounts eligible home batteries at the point of sale, and the discount steps down on a fixed schedule, so the same battery costs more each time it does. Victorian owner-occupiers may also qualify for the Solar Victoria panel rebate.</p><p>We handle the applications and the distributor paperwork. You pay the reduced price.</p></Rise></div><div className="rebate-links"><a href="https://www.dcceew.gov.au/energy/programs/cheaper-home-batteries"><span>Federal program<small>Cheaper Home Batteries</small></span><Arrow/></a><a href="https://www.solar.vic.gov.au/solar-panel-rebate"><span>Victorian households<small>Solar Victoria panel rebate</small></span><Arrow/></a><p>Eligibility and equipment requirements apply. Solar Victoria applies to Victorian properties only; Albury customers are covered by the federal programs. Confirm current requirements for your installation date.</p></div></section><Faq/><ContactBand/></main><Footer/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(businessSchema).replace(/</g,'\\u003c')}}/></>}
